name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo yum -y update
            sudo yum install -y httpd
            sudo systemctl start httpd
            sudo systemctl enable httpd
            sudo mv /home/ec2-user/* /var/www/html

      - name: Update AppSpec file and push
        run: |
          echo 'version: 0.0' > appspec.yml
          echo 'os: linux' >> appspec.yml
          echo 'resources:' >> appspec.yml
          echo '  - myResource:' >> appspec.yml
          echo '      - type: EC2' >> appspec.yml
          echo '        lifecycleEventHook:' >> appspec.yml
          echo '          ApplicationStop:' >> appspec.yml
          echo '            - location: scripts/stop_server.sh' >> appspec.yml
          echo '              timeout: 300' >> appspec.yml
          echo '          BeforeInstall:' >> appspec.yml
          echo '            - location: scripts/before_install.sh' >> appspec.yml
          echo '              timeout: 300' >> appspec.yml
          echo '          AfterInstall:' >> appspec.yml
          echo '            - location: scripts/after_install.sh' >> appspec.yml
          echo '              timeout: 300' >> appspec.yml
          echo '          ApplicationStart:' >> appspec.yml
          echo '            - location: scripts/start_server.sh' >> appspec.yml
          echo '              timeout: 300' >> appspec.yml

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add appspec.yml
          git commit -m "Update appspec.yml"
          git push
